server:
  port: 11000
  servlet:
    context-path: /voting

spring:
  application:
    name: voting
  datasource:
    url: jdbc:postgresql://localhost:5432/voting?sslMode=disable
    username: postgres
    password: 1211
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


